name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6.4
        name: Build & push Docker image
        with:
          image:  sonar-cnes-report
          tags: latest, ${{vars.SONAR_CNES_REPORT_VERSION_ARG}}
          buildArgs: SONAR_CNES_REPORT_VERSION=${{vars.SONAR_CNES_REPORT_VERSION_ARG}}
          registry: ghcr.io
          username: ivanmorenoj
          password: ${{ secrets.GITHUB_TOKEN }}
